{% set version = "0.0.6" %}


package:
  name: woodwork
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/woodwork/woodwork-{{ version }}.tar.gz
  sha256: e7df74397a3f3760084464ccf4247c8289c9a223d937d738a2d11b0fb6e7dc3d

build:
  entry_points:
    - woodwork = woodwork.__main__:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy >=1.19.1
    - pandas >=1.1.0
    - click >=7.1.2
    - scikit-learn >=0.21.3
    - pyarrow >=2.0.0
    - python >=3.6

test:
  imports:
    - woodwork
    - woodwork.tests
  requires:
    - pip >=20.2.2
    - pytest ==6.0.1
    - pytest-cov ==2.10.1
    - pytest-xdist ==2.1.0
    - boto3 >=1.10.45
    - moto >=1.3.14
    - smart_open >=1.8.4
    - ecdsa <=0.14.1
  source_files:
    - woodwork/tests/*
  commands:
    - pytest woodwork/tests
    - pip check

about:
  doc_url: https://woodwork.alteryx.com
  dev_url: https://github.com/Featurelabs/woodwork/
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Woodwork provides you with a common DataTable object to use with Featuretools, EvalML, and general ML.

extra:
  recipe-maintainers:
    - gsheni
    - thehomebrewnerd
