{% set version = "0.4.2" %}


package:
  name: woodwork
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/woodwork/woodwork-{{ version }}.tar.gz
  sha256: 4403046678741cc72ae78df8f7e148dc57ca0336ddb6a912baa90cdf5aa777e8

build:
  entry_points:
    - woodwork = woodwork.__main__:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - pandas >=1.2.0, <1.2.5
    - scikit-learn >=0.22
    - python >=3.7

test:
  imports:
    - woodwork
    - woodwork.tests
  requires:
    - pip >=20.2.2
    - pytest ==6.0.1
    - pytest-cov ==2.10.1
    - pytest-xdist ==2.1.0
    - mock >=4.0.3
    - boto3 >=1.10.45
    - moto >=1.3.14
    - werkzeug <2.0.0
    - smart_open >=5.0.0
    - pyarrow >=4.0.1
    - ecdsa <=0.14.1
    - rsa ==4.7.2
    - pyasn1 ==0.4.8
  source_files:
    - woodwork/tests/*
  commands:
    - pytest woodwork/tests
    - pip check

about:
  doc_url: https://woodwork.alteryx.com
  dev_url: https://github.com/alteryx/woodwork
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Woodwork provides a common typing namespace for using your existing DataFrames in Featuretools, EvalML, and general ML.


extra:
  recipe-maintainers:
    - gsheni
    - thehomebrewnerd
    - rwedge
    - tamargrey
