{% set version = "0.16.3" %}


package:
  name: woodwork
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/woodwork/woodwork-{{ version }}.tar.gz
  sha256: 952b92443adec98a0a6ec735868e342d56f44a2e2ce9370e7fcaa03e5928aeda

build:
  entry_points:
    - woodwork = woodwork.__main__:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - pandas >=1.3.0, <1.4.2
    - scikit-learn >=0.22
    - python-dateutil >=2.8.1
    - python >=3.7

test:
  imports:
    - woodwork
    - woodwork.tests
  requires:
    - pip >=21.3.1
    - pytest ==7.0.1
    - pytest-cov ==2.10.1
    - pytest-xdist ==2.1.0
    - boto3 >=1.10.45
    - moto >=3.0.7
    - smart_open >=5.0.0
    - pyarrow >=4.0.1
    - ecdsa <=0.14.1
    - rsa ==4.7.2
    - pyasn1 ==0.4.8
  source_files:
    - woodwork/tests/*
  commands:
    - pytest woodwork/tests
    - pip check

about:
  doc_url: https://woodwork.alteryx.com
  dev_url: https://github.com/alteryx/woodwork
  home: https://www.alteryx.com/open-source
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Woodwork provides a common typing namespace for using your existing DataFrames in Featuretools, EvalML, and general ML.


extra:
  recipe-maintainers:
    - gsheni
    - thehomebrewnerd
    - rwedge
    - tamargrey
    - dvreed77
    - jeff-hernandez
    - Cmancuso
    - bchen1116
    - ParthivNaresh
