{% set version = "0.10.0" %}


package:
  name: woodwork
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/woodwork/woodwork-{{ version }}.tar.gz
  sha256: 18e61334b32e239e296e43c3b32a41482531feb0a89b6176f95559d0a8ef032a

build:
  entry_points:
    - woodwork = woodwork.__main__:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - pandas >=1.3.0
    - scikit-learn >=0.22
    - python >=3.7

test:
  imports:
    - woodwork
    - woodwork.tests
  requires:
    - pip >=21.3.1
    - pytest ==6.0.1
    - pytest-cov ==2.10.1
    - pytest-xdist ==2.1.0
    - mock >=4.0.3
    - boto3 >=1.10.45
    - moto >=2.0.8
    - smart_open >=5.0.0
    - pyarrow >=4.0.1
    - ecdsa <=0.14.1
    - rsa ==4.7.2
    - pyasn1 ==0.4.8
  source_files:
    - woodwork/tests/*
  commands:
    - pytest woodwork/tests
    - pip check

about:
  doc_url: https://woodwork.alteryx.com
  dev_url: https://github.com/alteryx/woodwork
  home: https://www.alteryx.com/innovation-labs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Woodwork provides a common typing namespace for using your existing DataFrames in Featuretools, EvalML, and general ML.


extra:
  recipe-maintainers:
    - gsheni
    - thehomebrewnerd
    - rwedge
    - tamargrey
    - tuethan1999
    - davesque
    - jeff-hernandez
