{% set name = "woodwork" %}
{% set version = "0.31.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: 6ef82af1d5b6525b02efe6417c574c810cfdcc606cb266bd0d7fb17a1d066b67
  patches:                        # [win]
    - remove-absolute-path.patch  # [win]

build:
  number: 0
  skip: True  # [py<39]
  script:
    - del /s /f /q docs  # [win]
    - rm -rf docs  # [not win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - woodwork = woodwork.__main__:cli

requirements:
  build:                          # [win]
    - m2-patch                    # [win]
  host:
    - pip
    - python
    - setuptools >=61.0.0
    - wheel
  run:
    - importlib_resources >=5.10.0
    - numpy >=1.25.0
    - pandas >=2.0.0
    - python
    - python-dateutil >=2.8.2
    - scikit-learn >=1.1.0
    - scipy >=1.10.0

test:
  imports:
    - woodwork
    - woodwork.tests
  requires:
    - pip
# Skip tests on s390x; missing moto and pyarrow
{% if not s390x %}
    - boto3 >=1.34.32
    - moto >=5.0.0
    - pyarrow >=14.0.1
    - pytest >=7.0.1
    - pytest-xdist >=2.1.0
    - smart_open >=5.0.0
  source_files:
    - woodwork/tests/*
{% endif %}
  commands:
    - pytest woodwork/tests  # [not (s390x or win)]
    # pytest tmpdir fixture causing broken tests on Windows.
    - pytest woodwork/tests --ignore "woodwork/tests/accessor/test_serialization.py" --ignore "woodwork/tests/utils/test_read_file.py"  # [win]
    # docker-py has an exact pinning for pywin32 that cause pip check to fail.
    - pip check  # [not win]

about:
  doc_url: https://woodwork.alteryx.com
  dev_url: https://github.com/alteryx/woodwork
  home: https://www.alteryx.com/open-source
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Woodwork is a Python library that provides robust methods for managing and communicating data typing information.
  description: |
    Woodwork provides a common typing namespace for using your existing DataFrames in Featuretools,
    EvalML, and general ML. A Woodwork DataFrame stores the physical, logical, and semantic data
    types present in the data. In addition, it can store metadata about the data, allowing you to
    store specific information you might need for your application.

extra:
  recipe-maintainers:
    - machineAYX
    - simha104
    - petejanuszewski1
    - gsheni
    - thehomebrewnerd
    - rwedge
    - tamargrey
    - dvreed77
    - jeff-hernandez
    - Cmancuso
    - bchen1116
    - ParthivNaresh
